# Generated by Django 4.1.7 on 2023-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
