# Generated by Django 4.1.7 on 2023-03-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_held',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
